create table avis (
  id bigint generated by default as identity primary key,
  nom text not null,
  note integer not null check (note between 1 and 5),
  commentaire text not null,
  statut text not null default 'publie'
    check (statut in ('publie')),
  created_at timestamptz not null default now()
);

alter table avis enable row level security;

create policy "avis publics"
on avis
for select
using (true);

create policy "publier un avis"
on avis
for insert
with check (statut = 'publie');